import { lib, game, ui, get, ai, _status } from "../../../noname.js";
/* 【2026-09-30 修复】cshVoices 原由 extension.js 的模块作用域提供，拆出后必须自带 import。
   漏掉它会让**整个扩展加载失败**：translate 区块里有 `...cshVoices` 展开，
   运行时抛 ReferenceError: cshVoices is not defined。 */
import cshVoices from "../core/voices.js";
/* 武将分包：由 extension.js 的 package.character 机械拆出（P2，2026-09-30）。
   内容一字未改；补 import 是因为原作用域内的 get.* / cshVoices 等引用拆出后需自带。 */
export default {
        connect: true,
        character: {
            "csh_dz": {
                sex: "male",
                group: "shu",
                hp: 1,
                maxHp: 2,
                hujia: 2,
                skills: ["csh_yiwu","csh_douyan","csh_bizui"],
                img: "extension/池子魔将/image/csh_dz.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_dz.mp3"],
            },
            "csh_wn": {
                sex: "male",
                group: "qun",
                hp: 3,
                maxHp: 7,
                hujia: 2,
                skills: ["csh_ranshang","csh_duolve"],
                img: "extension/池子魔将/image/csh_wn.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_wn.mp3"],
                isZhugong: true,
            },
            "csh_sunshangxiang": {
                sex: "female",
                group: "wu",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_ssx_xiaoji","csh_ssx_pianzhu","csh_ssx_jiaozong"],
                img: "extension/池子魔将/image/csh_sunshangxiang.jpg",
                dieAudios: ["sunshangxiang"],
            },
            "csh_huangyueying": {
                sex: "female",
                group: "shu",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_hyy_jizhi","csh_hyy_linglong","csh_hyy_qicai"],
                img: "extension/池子魔将/image/csh_huangyueying.jpg",
                dieAudios: ["huangyueying"],
            },
            "csh_huaman": {
                sex: "female",
                group: "shu",
                hp: 3,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_manyi", "csh_xiangzhen", "csh_xizhan"],
                img: "extension/池子魔将/image/csh_huaman.webp",
            },
            "csh_yuangubafei": {
                sex: "male",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_bashen"],
                img: "extension/池子魔将/image/csh_yuangubafei.jpg",
                dieAudios: ["re_weiyan"],
            },
            "csh_xingganning": {
                sex: "male",
                group: "wu",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_jinfan", "csh_sheque"],
                img: "extension/池子魔将/image/csh_xingganning.jpg",
                dieAudios: ["ganning"],
            },
            "csh_liximing": {
                sex: "male",
                group: "qun",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_xiantu"],
                img: "extension/池子魔将/image/csh_liximing.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_liximing.mp3"],
            },
            "csh_mingrixiang": {
                sex: "female",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_tongbu"],
                img: "extension/池子魔将/image/csh_mingrixiang.jpg",
                dieAudios: ["ext:池子魔将/audio/skill/csh_asuka_14.mp3"],
            },


            "csh_jzh": {
                sex: "male",
                group: "wu",
                hp: 5,
                maxHp: 5,
                skills: ["csh_kurou","csh_zhaxiang"],
                img: "extension/池子魔将/image/csh_jzh.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_jzh.mp3"],
                hujia: 1,
            },
            "csh_qw": {
                sex: "male",
                group: "wei",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_wuzhen","csh_qiai","csh_sbweimu"],
                img: "extension/池子魔将/image/csh_qw.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_qw.mp3"],
                isZhugong: true,
            },
            "csh_jjxs": {
                sex: "male",
                group: "wu",
                hp: 3,
                maxHp: 4,
                skills: ["csh_yingzipojun","csh_pojun12"],
                img: "extension/池子魔将/image/csh_jjxs.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_jjxs.mp3"],
                hujia: 1,
            },
            "csh_mmhz": {
                sex: "male",
                group: "shu",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_liegong"],
                img: "extension/池子魔将/image/csh_mmhz.webp",
                dieAudios: ["shen_huangzhong"],
            },
            "csh_wlk": {
                sex: "male",
                group: "qun",
                hp: 3,
                maxHp: 5,
                hujia: 1,
                skills: ["csh_qianju","csh_kuanggu","csh_langxi1x"],
                img: "extension/池子魔将/image/csh_wlk.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_wlk.mp3"],
            },
            "csh_sx": {
                sex: "male",
                group: "qun",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_xiongluan","csh_junchi","csh_zhansong"],
                img: "extension/池子魔将/image/csh_sx.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_sx.mp3"],
            },
            "csh_gdsn": {
                sex: "female",
                group: "qun",
                hp: 1,
                maxHp: 2,
                hujia: 1,
                skills: ["csh_longhun","csh_yajiao"],
                img: "extension/池子魔将/image/csh_gdsn.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_gdsn.mp3"],
            },
            "csh_gjs": {
                sex: "male",
                group: "shen",
                hp: 1,
                maxHp: 1,
                skills: ["csh_xiangbin","csh_daorui","csh_xianghong"],
                img: "extension/池子魔将/image/csh_gjs.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_gjs.mp3"],
                isAiForbidden: true,
            },
            "csh_gy": {
                sex: "female",
                group: "shu",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_fangjian123"],
                img: "extension/池子魔将/image/csh_gy.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_gy.mp3"],
            },
            "csh_bfsm": {
                sex: "male",
                group: "wu",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_dcjianying","csh_rendao","csh_xielei"],
                img: "extension/池子魔将/image/csh_bfsm.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_bfsm.mp3"],
                isZhugong: true,
            },
            "csh_ls": {
                sex: "male",
                group: "wu",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_jiaomeng","csh_jiejian","csh_jiangxian"],
                img: "extension/池子魔将/image/csh_ls.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_ls.mp3"],
            },
            "csh_sj": {
                sex: "male",
                group: "wu",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_hunying","csh_zhiba","csh_shexiao","csh_jsrgpingtao"],
                img: "extension/池子魔将/image/csh_sj.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_sj.mp3"],
                isZhugong: true,
            },
            "csh_sq": {
                sex: "male",
                group: "wu",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_zhiheng","csh_hsshezuo","csh_jianwu","csh_xishou"],
                img: "extension/池子魔将/image/csh_sq.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_sq.mp3"],
                isZhugong: true,
            },
            "csh_vxs": {
                sex: "female",
                group: "wu",
                hp: 2,
                maxHp: 2,
                hujia: 1,
                skills: ["csh_liangge","csh_guimou"],
                img: "extension/池子魔将/image/csh_vxs.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_vxs.mp3"],
            },
            "csh_msmy": {
                sex: "male",
                group: "jin",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_sbaiyin","csh_pt","csh_renshen","csh_jikui"],
                img: "extension/池子魔将/image/csh_msmy.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_msmy.mp3"],
            },
            "csh_mlb": {
                sex: "male",
                group: "qun",
                hp: 4,
                maxHp: 5,
                hujia: 1,
                skills: ["csh_lvbu_baonu","csh_sbwushuang","csh_chitu"],
                img: "extension/池子魔将/image/csh_mlb.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_mlb.mp3"],
                isZhugong: true,
            },
            "csh_yy": {
                sex: "female",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_fengyan","csh_renfa23","csh_yaoji"],
                img: "extension/池子魔将/image/csh_yy.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_yy.mp3"],
            },
            "csh_bzt": {
                sex: "male",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_shentou234"],
                img: "extension/池子魔将/image/csh_bzt.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_bzt.mp3"],
            },
            "csh_lr": {
                sex: "male",
                group: "shen",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_jinghua","csh_shenyun"],
                img: "extension/池子魔将/image/csh_lr.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_lr.mp3"],
                isZhugong: true,
            },
            "csh_szc": {
                sex: "male",
                group: "wei",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_wuwei","csh_huishi","csh_guanyu_wusheng"],
                img: "extension/池子魔将/image/csh_szc.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_szc.mp3"],
            },
            "csh_mlm": {
                sex: "male",
                group: "qun",
                hp: 3,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_keji","csh_keji1","csh_niming"],
                img: "extension/池子魔将/image/csh_mlm.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_mlm.mp3"],
            },
            "csh_wy": {
                sex: "male",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_leitong","csh_yiyuan","csh_buhei"],
                img: "extension/池子魔将/image/csh_wy.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_wy.mp3"],
            },
            "csh_ae": {
                sex: "male",
                group: "shu",
                hp: 1,
                maxHp: 8,
                hujia: 1,
                skills: ["csh_ss","csh_yn"],
                img: "extension/池子魔将/image/csh_ae.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_ae.mp3"],
            },
            "csh_mzj": {
                sex: "female",
                group: "wei",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_reqiuyuan","csh_guidao129","csh_reluoshen"],
                img: "extension/池子魔将/image/csh_mzj.webp",
                dieAudios: ["zhenji"],
            },
            "csh_chengpu": {
                sex: "male",
                group: "wu",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_lihuo","csh_wutui","csh_rechunlao","csh_jishe"],
                img: "extension/池子魔将/image/csh_chengpu.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_chengpu.mp3"],
            },
            "csh_zhangbao": {
                sex: "male",
                group: "qun",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_rezhoufu","csh_baofutou"],
                img: "extension/池子魔将/image/csh_zhangbao.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_zhangbao.mp3"],
                isZhugong: true,
            },
            "csh_caoang": {
                sex: "male",
                group: "wei",
                hp: 1,
                maxHp: 3,
                hujia: 2,
                skills: ["csh_jili","csh_kaiqi","csh_tuofan"],
                img: "extension/池子魔将/image/csh_caoang.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_caoang.mp3"],
            },
            "csh_guohuai": {
                sex: "male",
                group: "wei",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_twjingce","csh_chengce"],
                img: "extension/池子魔将/image/csh_guohuai.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_guohuai.mp3"],
            },
            "csh_xushu": {
                sex: "male",
                group: "shu",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_qianxin","csh_rezhuhai","csh_zhichi"],
                img: "extension/池子魔将/image/csh_xushu.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_xushu.mp3"],
            },
            "csh_zhonghui": {
                sex: "male",
                group: "qun",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_zhonghui_tiaoxin","csh_tongji","csh_quanji","csh_zili"],
                img: "extension/池子魔将/image/csh_zhonghui.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_zhonghui.mp3"],
            },
            "csh_xuchu": {
                sex: "male",
                group: "wei",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_mingjue","csh_luoyi","csh_zhanlai"],
                img: "extension/池子魔将/image/csh_xuchu.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_xuchu.mp3"],
            },
            "csh_weizheng": {
                sex: "male",
                group: "wei",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_shuaiyan","csh_zhijian"],
                img: "extension/池子魔将/image/csh_weizheng.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_weizheng.mp3"],
            },
            "csh_zhuzhi": {
                sex: "male",
                group: "shen",
                hp: 4,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_zhangang","csh_chengqiang1","csh_kuiwei"],
                img: "extension/池子魔将/image/csh_zhuzhi.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_zhuzhi.mp3"],
            },
            "csh_ngwt": {
                sex: "male",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_tianjing","csh_yuli","csh_zidian"],
                img: "extension/池子魔将/image/csh_ngwt.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_ngwt.mp3"],
            },
            "csh_misida": {
                sex: "male",
                group: "qun",
                hp: 4,
                maxHp: 4,
                hujia: 4,
                skills: ["csh_daoyan1"],
                img: "extension/池子魔将/image/csh_misida.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_misida.mp3"],
            },
            "csh_zuozhu": {
                sex: "male",
                group: "qun",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_xielun","csh_renjin","csh_xuzuo"],
                img: "extension/池子魔将/image/csh_zuozhu.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_zuozhu.mp3"],
            },
            "csh_bin": {
                sex: "male",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_risheng","csh_gangbei","csh_shiyi"],
                img: "extension/池子魔将/image/csh_bin.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_bin.mp3"],
            },
            "csh_maochao": {
                sex: "male",
                group: "qun",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_shuzhan","csh_liangwang","csh_qingzi"],
                img: "extension/池子魔将/image/csh_maochao.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_maochao.mp3"],
            },
            "csh_guansuo": {
                sex: "male",
                group: "shu",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_gongao","csh_zhugefuhun","csh_weizhong"],
                img: "extension/池子魔将/image/csh_guansuo.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_guansuo.mp3"],
            },
            "csh_zhaoxiang": {
                sex: "female",
                group: "shu",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_fanghun","csh_rongbei","csh_fuji223"],
                img: "extension/池子魔将/image/csh_zhaoxiang.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_zhaoxiang.mp3"],
            },
            "csh_zhuran": {
                sex: "male",
                group: "wu",
                hp: 2,
                maxHp: 2,
                hujia: 1,
                skills: ["csh_danshou"],
                img: "extension/池子魔将/image/csh_zhuran.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_zhuran.mp3"],
            },
            "csh_yujin": {
                sex: "male",
                group: "wei",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_jieyue"],
                img: "extension/池子魔将/image/csh_yujin.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_yujin.mp3"],
            },
            "csh_handang": {
                sex: "male",
                group: "wu",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_niluan","csh_xiaoxi_hansui","csh_spweiwu"],
                img: "extension/池子魔将/image/csh_handang.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_handang.mp3"],
            },
            "csh_caiyan": {
                sex: "female",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_yusuo","csh_qiege"],
                img: "extension/池子魔将/image/csh_caiyan.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_caiyan.mp3"],
            },
            "csh_simahui": {
                sex: "male",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_shuijing","csh_zhiyin","csh_jingfu"],
                img: "extension/池子魔将/image/csh_simahui.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_simahui.mp3"],
            },
            "csh_wenyang": {
                sex: "male",
                group: "wei",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_poyin","csh_chuanfa"],
                img: "extension/池子魔将/image/csh_wenyang.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_wenyang.mp3"],
            },
            "csh_dengai": {
                sex: "male",
                group: "wei",
                hp: 3,
                maxHp: 4,
                skills: ["csh_zishu","csh_retuntian","csh_zaoxian"],
                img: "extension/池子魔将/image/csh_dengai.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_dengai.mp3"],
                hujia: 1,
            },
            "csh_gaogan": {
                sex: "female",
                group: "wei",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_juguan","csh_manyujinsuwu"],
                img: "extension/池子魔将/image/csh_gaogan.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_gaogan.mp3"],
                isZhugong: true,
            },
            "csh_lifeng": {
                sex: "male",
                group: "shu",
                hp: 1,
                maxHp: 1,
                hujia: 1,
                skills: ["csh_dctunchu","csh_zichen","csh_lifeng_shuliang"],
                img: "extension/池子魔将/image/csh_lifeng.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_lifeng.mp3"],
            },
            "csh_caochun": {
                sex: "male",
                group: "wei",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_xinshanjia"],
                img: "extension/池子魔将/image/csh_caochun.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_caochun.mp3"],
            },
            "csh_shamoke": {
                sex: "male",
                group: "shu",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_gzjili","csh_xianxiamanyong"],
                img: "extension/池子魔将/image/csh_shamoke.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_shamoke.mp3"],
            },
            "csh_zhangning": {
                sex: "female",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_huangtian1","csh_difa12"],
                img: "extension/池子魔将/image/csh_zhangning.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_zhangning.mp3"],
            },
            "csh_lidian": {
                sex: "male",
                group: "wei",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_xunxun","csh_xinwangxi"],
                img: "extension/池子魔将/image/csh_lidian.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_lidian.mp3"],
            },
            "csh_lvlingqi": {
                sex: "female",
                group: "qun",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_yannv1","csh_zhuangrong12"],
                img: "extension/池子魔将/image/csh_lvlingqi.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_lvlingqi.mp3"],
            },
            "csh_wolongzhuge": {
                sex: "male",
                group: "shu",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_huoji","csh_kanpo","csh_xingyou"],
                img: "extension/池子魔将/image/csh_wolongzhuge.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_wolongzhuge.mp3"],
            },
            "csh_dongzhuo": {
                sex: "male",
                group: "qun",
                hp: 14,
                maxHp: 29,
                skills: ["csh_bianduan","csh_benghuai","csh_baowei"],
                img: "extension/池子魔将/image/csh_dongzhuo.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_dongzhuo.mp3"],
                isZhugong: true,
            },
            "csh_chendao": {
                sex: "male",
                group: "shu",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_wanglie","csh_maojiang"],
                img: "extension/池子魔将/image/csh_chendao.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_chendao.mp3"],
            },
            "csh_lukang": {
                sex: "male",
                group: "wu",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_kangli","csh_stargangyi"],
                img: "extension/池子魔将/image/csh_lukang.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_lukang.mp3"],
            },
            "csh_xurong": {
                sex: "male",
                group: "qun",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_xionghuo","csh_sxrmzhaduo"],
                img: "extension/池子魔将/image/csh_xurong.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_xurong.mp3"],
            },
            "csh_doudou": {
                sex: "male",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_wozhan","csh_qiangu"],
                img: "extension/池子魔将/image/csh_doudou.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_doudou.mp3"],
                isZhugong: true,
            },
            "csh_zhugeke": {
                sex: "male",
                group: "wu",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_aocai","csh_duwu"],
                img: "extension/池子魔将/image/csh_zhugeke.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_zhugeke.mp3"],
            },
            "csh_nailong_juexing": {
                sex: "male",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_nailongjuexing","csh_daxiao"],
                img: "extension/池子魔将/image/csh_nailong_juexing.jpg",
                isZhugong: true,
            },
            "csh_chengyu": {
                sex: "male",
                group: "wei",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_shefu666","csh_benyu"],
                img: "extension/池子魔将/image/csh_chengyu.webp",
                dieAudios: ["ext:池子魔将/audio/die/csh_chengyu.mp3"],
            },
            "csh_shanyuezhiyin": {
                sex: "male",
                group: "shen",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_aoenyuyan","csh_aoenduandao","csh_aoenyidao"],
                img: "extension/池子魔将/image/csh_shanyuezhiyin.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_shanyuezhiyin.mp3"],
                isZhugong: true,
            },
            "csh_guanyinping": {
                sex: "female",
                group: "shu",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_sxrmyinmou","csh_dragxueji"],
                img: "extension/池子魔将/image/csh_guanyinping.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_guanyinping.mp3"],
            },
            "csh_realityfanghao": {
                sex: "male",
                group: "shen",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_fanghaoqibing","csh_sbhunzi"],
                dieAudios: ["ext:池子魔将/audio/die/csh_realityfanghao.mp3"],
                img: "extension/池子魔将/image/csh_realityfanghao.webp",
                isZhugong: true,
            },
            "csh_feibijiubi": {
                sex: "female",
                group: "shen",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_xinfu_duanfa","csh_feibininghui"],
                isZhugong: true,
                dieAudios: ["ext:池子魔将/audio/die/csh_feibijiubi.mp3"],
                img: "extension/池子魔将/image/csh_feibijiubi.jpg",
            },
            "csh_zhugeqing": {
                sex: "male",
                group: "shu",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_qimen","csh_zhugefencheng"],
                isZhugong: true,
                img: "extension/池子魔将/image/csh_zhugeqing.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_zhugeqing.mp3"],
            },
            "csh_moteng": {
                sex: "male",
                group: "qun",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_xumeng", "csh_pinju", "csh_shie"],
                img: "extension/池子魔将/image/csh_moteng.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_moteng.mp3"],
            },
            "csh_daaixianzun": {
                sex: "male",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_chunqiu","csh_xiansha","csh_fangyuan_hengshou"],
                dieAudios: ["ext:池子魔将/audio/die/csh_daaixianzun.mp3"],
                img: "extension/池子魔将/image/csh_daaixianzun.jpg",
            },
            "csh_zhangxingcai": {
                sex: "female",
                group: "shu",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_zhangxingcai_qiangwu","csh_zhangxingcai_shenxian"],
                dieAudios: ["zhangxingcai"],
                img: "extension/池子魔将/image/csh_zhangxingcai.webp",
            },
            "csh_jieluji": {
                sex: "male",
                group: "wu",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_jieluji_gailan","csh_jieluji_fennu"],
                dieAudios: ["luji"],
                img: "extension/池子魔将/image/csh_jieluji.webp",
            },
            "csh_youhabahe": {
                sex: "male",
                group: "shen",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_youhabahe_quanzhi","csh_youhabahe_shengbie"],
                img: "extension/池子魔将/image/csh_youhabahe.jpg",
            },
            "csh_shencaozhi": {
                sex: "male",
                group: "shen",
                hp: 1,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_qibu"],
                img: "extension/池子魔将/image/csh_shencaozhi.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_shencaozhi.mp3"],
            },
            "csh_shenzhugeguo": {
                sex: "female",
                group: "shen",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_binan","csh_xiudao","csh_feisheng"],
                img: "extension/池子魔将/image/csh_shenzhugeguo.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_shenzhugeguo.mp3"],
            },
            "csh_dabing": {
                sex: "male",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_dabing_qirui","csh_dabing_shicai","csh_dabing_fenchao"],
                img: "extension/池子魔将/image/csh_dabing.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_dabing.mp3"],
            },
            "csh_modekaisa": {
                sex: "male",
                group: "qun",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_pomie","csh_mingdun","csh_lunjing"],
                dieAudios: ["ext:池子魔将/audio/die/csh_modekaisa.mp3"],
                img: "extension/池子魔将/image/csh_modekaisa.jpg",
            },
            "csh_donk": {
                sex: "male",
                group: "qun",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_yumiao","csh_yaqiang","csh_saozhuan"],
                dieAudios: ["ext:池子魔将/audio/die/csh_donk.mp3"],
                img: "extension/池子魔将/image/csh_donk.jpg",
            },
            "csh_lamosi": {
                sex: "male",
                group: "qun",
                hp: 4,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_cijia","csh_chaogong"],
                img: "extension/池子魔将/image/csh_lamosi.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_lamosi.mp3"],
            },
            "csh_zhouchu": {
                sex: "male",
                group: "wu",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_xianghai","csh_chuhai"],
                img: "extension/池子魔将/image/csh_zhouchu.jpg",
            },
            "csh_yangjian": {
                sex: "male",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_yangzhi","csh_guiyan"],
                img: "extension/池子魔将/image/csh_yangjian.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_yangjian.mp3"], // 语音重做：死了？……我死的次数会少吗（皮肤引用同一文件一并生效）
            },
            "csh_sake": {
                sex: "male",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_huanxiang","csh_zhali"],
                img: "extension/池子魔将/image/csh_sake.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_sake.mp3"],
            },
            "csh_kuisangti": {
                sex: "male",
                group: "qun",
                hp: 3,
                maxHp: 4,
                hujia: 0,
                skills: ["csh_tuofu","csh_anzi"],
                img: "extension/池子魔将/image/csh_kuisangti.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_kuisangti1.mp3", "ext:池子魔将/audio/die/csh_kuisangti2.mp3"],
            },
            "csh_sailasi": {
                sex: "male",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_daodao","csh_yongshuang"],
                img: "extension/池子魔将/image/csh_sailasi.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_sailasi1.mp3", "ext:池子魔将/audio/die/csh_sailasi2.mp3"],
            },
            "csh_theshy": {
                sex: "male",
                group: "qun",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_theshy_xueren", "csh_theshy_biechi"],
                img: "extension/池子魔将/image/csh_theshy.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_theshy.mp3"],
            },
            "csh_diaochan": {
                sex: "female",
                group: "qun",
                hp: 2,
                maxHp: 3,
                hujia: 1,
                skills: ["csh_yunming", "csh_ziyan"],
                img: "extension/池子魔将/image/csh_diaochan.webp",
                dieAudios: ["diaochan"],
            },
            "csh_zywoo": {
                sex: "male",
                group: "shen",
                hp: 3,
                maxHp: 4,
                hujia: 1,
                skills: ["csh_jiagiang", "csh_goute"],
                img: "extension/池子魔将/image/csh_zywoo.jpg",
                dieAudios: ["ext:池子魔将/audio/die/csh_zywoo.mp3"],
            },

            "csh_pingfan": {
                sex: "male",
                group: "shu",
                hp: 4,
                maxHp: 4,
                skills: ["csh_jilei", "csh_huyou"],
                img: "extension/池子魔将/image/csh_pingfan.jpg",
            },
        },
        translate: {
            ...cshVoices,
            "csh_theshy": "姜大哥",
            "csh_zywoo": "载物",
            "csh_pingfan": "平凡之人",
            "csh_jilei": "积累",
            "csh_jilei_info": "锁定技。<br>回合开始时，你获得1枚「积」。你的摸牌阶段摸牌数+X，手牌上限+X（X为「积」的数量）。",
            "csh_huyou": "护佑",
            "csh_huyou_info": "使命技。<br>成功：第一轮结束时，若你存活，你获得1枚「带子」，将<noname-poptip poptip = csh_qiangbao></noname-poptip>从游戏外置入你的宝物栏。",
            "csh_daizi": "带子",
            "csh_daizi_info": "",
            "csh_niuma": "牛马",
            "csh_niuma_info": "持恒技，锁定技。<br>你的额定摸牌数+2。",
            "csh_qiangbao": "襁褓",
            "csh_qiangbao_info": "自你获得此牌起，再经过3个全局轮次后，若此牌仍在你的装备区，你失去<noname-poptip poptip = csh_jilei></noname-poptip>，获得<noname-poptip poptip = csh_niuma></noname-poptip>（武将牌上显示剩余轮数）。<br>当此牌离开你的装备区时，将此牌移出游戏；你失去「带子」，势力改为群，摸X张牌（X为你的体力上限），并获得「襁褓·余韵」。提前离开时保留〖积累〗。",
            "csh_qiangbao_skill_info": "当此牌离开装备区时，将此牌移出游戏；你失去「带子」，势力改为群，摸X张牌（X为体力上限），并获得「襁褓·余韵」。提前离开时保留〖积累〗。",
            "csh_qiangbao_sha_info": "你使用【杀】无距离与次数限制，不能被响应；你使用【杀】造成伤害时，你失去1点体力。",
            "csh_qiangbao_count_info": "显示【襁褓】转为〖牛马〗的剩余全局轮次。",
            "csh_qiangbao_sha_cost": "襁褓·余韵",
            "csh_daizi_damage": "带子",
            "csh_jilei_draw": "积累",
            "csh_huyou_success": "护佑",
            "csh_huyou_niuma": "护佑",
            "csh_qiangbao_skill": "襁褓",
            "csh_qiangbao_sha": "襁褓",

            "csh_jiagiang": "架枪",
            "csh_jiagiang_info": "出牌阶段限一次。当你使用【杀】或黑色牌指定其他角色为目标后，你可令其中一名目标选择一项：<br>①交给你一张与此牌类型相同的牌；<br>②弃置两张与此牌类型不同的牌；<br>③此牌<span style=\"color:#ff8a7a\">不可被响应</span>，你本回合使用【杀】的次数<span style=\"color:#7dffa0\">+1</span>。",
            "csh_goute": "构特",
            "csh_goute_info": "准备阶段，你选择将装备区里的武器替换为下列衍生装备之一（弹药为0的武器本局不能再选）。<br><br><span style=\"color:#e8c878\"><noname-poptip poptip = csh_daju></noname-poptip></span><br><span style=\"color:#9ec8ff\"><noname-poptip poptip = csh_ak47></noname-poptip></span><br><span style=\"color:#f0b060\"><noname-poptip poptip = csh_shaying></noname-poptip></span>",
            "csh_jiagiang_sha": "架枪",
            "csh_jiagiang_sha_info": "本回合使用【杀】的次数+1。",
            "csh_goute_blocksha": "拉栓",
            "csh_goute_blocksha_info": "不能使用【杀】（仍可打出以响应）。",
            "csh_daju_skill": "大狙",
            "csh_shaying_skill": "沙鹰",
            "csh_ak47_skill": "AK-47",
            "csh_huangshen": "晃身",
            "csh_huangshen_info": "每回合限一次，其他角色使用牌结算后，你可消耗1点弹药，插入一个出牌阶段。此出牌阶段结束后，有20%概率对该角色造成1点伤害。",
            "csh_qieqiang": "切枪",
            "csh_qieqiang_info": "若上次由大狙切换至沙鹰，你使用或打出牌后可立刻切换回大狙并解除「拉栓」；若上次由AK-47切换至沙鹰，你使用或打出牌后可切换回AK-47并摸两张牌。",
            "csh_diaochan": "貂蝉",
            "csh_yunming": "允命",
            "csh_yunming_info": "游戏开始时，你摸两张牌，然后依次选择两名其他角色（身份局不能选择主公）：先选择的角色获得技能〖董卓〗，后选择的角色获得技能〖吕布〗。直到其中一名角色阵亡：这些角色使用【杀】时只能指定彼此为目标，且其互相计算距离时始终视为1。更换武将牌不使此效果失效；若因此【杀】无合法目标，则其不能使用【杀】。",
            "csh_ziyan": "姿颜",
            "csh_ziyan_info": "准备阶段，若有其他角色装备武器，你可以视为使用一张【借刀杀人】；结束阶段，你可以摸X张牌（X为场上已受伤角色数，且至少为1）。",
            "csh_yunming_dongzhuo": "董卓",
            "csh_yunming_dongzhuo_info": "锁定技。①结束阶段，若你的体力上限小于8，你增加1点体力上限；②准备阶段，若你的体力上限不小于8，你将武将牌替换为界限突破董卓，体力与体力上限回复至界董卓的标准值，然后失去此技能（死斗契约保留）。",
            "csh_yunming_lvbu": "吕布",
            "csh_yunming_lvbu_info": "锁定技。①若你的武器栏为空，你视为装备着【方天画戟】；②当你进入濒死状态时，你将武将牌替换为界限突破吕布，体力与体力上限回复至界吕布的标准值，然后失去此技能（死斗契约保留）；③当一名其他角色使用【杀】造成伤害后，你获得其一张牌，然后其视为对你使用一张【决斗】。",
            "csh_yunming_pact": "死斗",
            "csh_yunming_pact_info": "你与另一名角色处于死斗契约中：使用【杀】只能指定彼此为目标，互相距离视为1。",
            "csh_yunming_fangtian": "方天",
            "csh_yunming_fangtian_info": "锁定技，你的武器栏为空时，视为装备着【方天画戟】。",
            "csh_sunshangxiang": "孙尚香",
            "csh_daju": "大狙",
            "none": "虚拟",
            "nosuit": "虚拟",
            "csh_daju_info": "①攻击范围为9。②你的手牌中的武器牌均视为【无中生有】。③你使用【杀】造成伤害时，此伤害改为目标当前体力值；若你与目标距离大于1，则改为由你与目标之间最短路径上最靠近目标的角色承受此伤害。④当你使用【杀】造成伤害后，你获得「拉栓」。⑤此牌有5点弹药。你使用【杀】造成伤害后，弹药-1；弹药为0时，无法再选择大狙。⑥锁定技，当你失去装备区里的此牌时，销毁之。",
            "csh_shaying": "沙鹰",
            "csh_shaying_info": "①攻击范围为9。②你的手牌中的武器牌均视为【无中生有】。③晃身：每回合限一次，当其他角色使用牌结算结束后，你可以消耗1点弹药，于此牌结算后插入一个出牌阶段。④切枪：当你使用或打出牌后，若你上一把装备的是【大狙】，你可以切换回【大狙】并解除「拉栓」；若上一把装备的是【AK-47】，你可以切换回【AK-47】并摸两张牌。⑤此牌有7点弹药。你发动「晃身」时弹药-1；弹药为0时，无法再选择沙鹰。⑥锁定技，当你失去装备区里的此牌时，销毁之。",
            "csh_ak47": "AK-47",
            "csh_ak47_info": "①攻击范围为9。②你的手牌中的武器牌均视为【无中生有】。③出牌阶段限一次，你可以消耗1点弹药，视为使用一张任意属性的【杀】（你选择属性）。④此牌有30点弹药。你发动上述效果时弹药-1；弹药为0时，无法再选择AK-47。⑤锁定技，当你失去装备区里的此牌时，销毁之。",
            "csh_ice_sha": "冰杀",
            "csh_ice_sha_info": "属性为冰的【杀】。当此【杀】即将对一名角色造成伤害时（非连环传导），若其有能被你弃置的牌，你可以防止此<span style='color:#e74c3c'>伤害</span>，改为依次弃置其两张牌。",
            "csh_xiaoxi_hansui": "骁袭",
            "csh_xiaoxi_hansui_info": "你可以将一张黑色牌当刺【杀】使用或打出。",
            "csh_xiaoxi_hansui_cda": "骁袭",
            "csh_xiaoxi_hansui_cda_info": "",
            "csh_dz": "丁真",
            "csh_wn": "兀突骨",
            "csh_jzh": "黄盖",
            "csh_qw": "贾诩",
            "csh_jjxs": "界界徐盛",
            "csh_mmhz": "谋谋黄忠",
            "csh_liegong": "烈弓",
            "csh_liegong_info": "<span style='color:#e8c872;'>①</span>每当你使用牌、或成为其他角色使用牌的目标后，你获得X点<span style='color:#41e07e;'><b>弦</b></span>（X为该牌点数，弦上限为100）。<br><span style='color:#e8c872;'>②</span>出牌阶段内，当你使用【杀】指定<span style='color:#ff5733;'><b>唯一目标</b></span>后，你可以<span style='color:#ff5733;'><b>释放所有弦</b></span>，根据释放弦数获得对应效果。",
            "csh_wanshi": "万石",
            "csh_wanshi_info": "锁定技。①若你的武器栏为空，你视为装备着<noname-poptip poptip = qilin></noname-poptip>；②若你的防具栏为空，你视为装备着<noname-poptip poptip = tengjia></noname-poptip>。",
            "csh_lieqiong": "裂穹",
            "csh_lieqiong_info": `当你对一名其他角色造成伤害后，你可以击伤其一个部位："${get.poptip({
                id: "csh_lieqiong_pos_hand",
                name: "力烽",
                type: "character",
                info: "令其随机弃置一半手牌（向上取整）。",
            })}"、"${get.poptip({
                id: "csh_lieqiong_pos_leg",
                name: "地机",
                type: "character",
                info: "令其下一次受到的伤害+1直到其下个回合结束。",
            })}"、"${get.poptip({
                id: "csh_lieqiong_pos_chest",
                name: "中枢",
                type: "character",
                info: "令其使用的下一张牌无效直到其回合结束。",
            })}"、"${get.poptip({
                id: "csh_lieqiong_pos_abdomen",
                name: "气海",
                type: "character",
                info: "令其不能使用或打出红桃牌直到其下个回合结束。",
            })}"；若你于此回合内已击伤过该角色，则出现"${get.poptip({
                id: "csh_lieqiong_pos_head",
                name: "天冲",
                type: "character",
                info: "令其失去所有体力，若其因此死亡，你增加1点体力上限。",
            })}"选项。`,
            "csh_wlk": "沃里克",
            "csh_sx": "张绣",
            "csh_gdsn": "高达姬",
            "csh_gjs": "鬼剑士",
            "csh_gy": "廖英",
            "csh_bfsm": "周瑜",
            "csh_jieluji": "陆绩",
            "csh_jieluji_prefix": "池",
            "csh_ls": "鲁肃",
            "csh_sj": "孙坚",
            "csh_sq": "孙权",
            "csh_vxs": "孙鲁班",
            "csh_msmy": "司马懿",
            "csh_mlb": "吕布",
            "csh_yy": "卑弥呼",
            "csh_bzt": "胡车儿",
            "csh_lr": "蓝染",
            "csh_szc": "关羽",
            "csh_mlm": "吕蒙",
            "csh_wy": "王也",
            "csh_ae": "张飞",
            "csh_mzj": "甄宓",
            "csh_chengpu": "程普",
            "csh_zhangbao": "张宝",
            "csh_caoang": "曹昂",
            "csh_guohuai": "郭淮",
            "csh_xushu": "徐庶",
            "csh_zhonghui": "钟会",
            "csh_xuchu": "许褚",
            "csh_weizheng": "魏征",
            "csh_zhuzhi": "加里奥",
            "csh_ngwt": "张角",
            "csh_misida": "米斯达",
            "csh_maochao": "马超",
            "csh_guansuo": "关索",
            "csh_zhaoxiang": "赵襄",
            "csh_zhuran": "朱然",
            "csh_yujin": "于禁",
            "csh_handang": "韩当",
            "csh_caiyan": "蔡琰",
            "csh_simahui": "司马徽",
            "csh_wenyang": "文鸯",
            "csh_dengai": "邓艾",
            "csh_gaogan": "清河公主",
            "csh_lifeng": "李丰",
            "csh_caochun": "曹纯",
            "csh_shamoke": "沙摩柯",
            "csh_zhangning": "张宁",
            "csh_lidian": "李典",
            "csh_lvlingqi": "吕玲绮",
            "csh_wolongzhuge": "卧龙诸葛",
            "csh_dongzhuo": "董卓",
            "csh_chendao": "陈到",
            "csh_lukang": "陆抗",
            "csh_lamosi": "拉莫斯",
            "池子魔将": "池子魔将",
            "mode_extension_池子魔将": "池子魔将",
            "csh_xurong": "徐荣",
            "csh_doudou": "豆豆",
            "csh_moteng": "魔腾",
            "csh_xumeng": "虚梦",
            "csh_pinju": "品惧",
            "csh_shie": "释噩",
            "csh_e": "噩",
            "csh_zhugeke": "诸葛恪",
            "csh_nailong_juexing": "奶龙",
            "csh_chengyu": "程昱",
            "csh_shanyuezhiyin": "奥恩",
            "csh_guanyinping": "关银屏",
            "csh_realityfanghao": "方圣帝君",
            "csh_feibijiubi": "菲比",
            "csh_zhugeqing": "诸葛青",
            "csh_cuifeng": "摧锋 · 输出",
            "csh_jingting": "惊霆 · 爆发",
            "csh_fulan": "缚澜 · 强控",
            "csh_huichuan": "暗涌 · 干扰",
            "csh_fuguang": "扶光 · 辅助",
            "csh_jinhuo": "磐石 · 防御",
            "csh_zhoutian": "薪火 · 成长",
            "csh_qunyou_lunwai": "群友·共创",
            "csh_pingxing_shang": "平行时空·上",
            "csh_pingxing_xia": "平行时空·下",
            "csh_pingxing_yinjian": "平行时空·阴间",
            "csh_daaixianzun": "大爱仙尊",
            "csh_youhabahe": "友哈巴赫",
            "csh_shencaozhi": "神曹植",
            "csh_shenzhugeguo": "神诸葛果",
            "csh_dabing": "大冰",
            "csh_zhangxingcai": "张星彩",
            "csh_modekaisa": "莫德凯撒",
            "csh_donk": "洞克",
            "csh_zhouchu": "周处",
            "#csh_zhouchu:die": "三害未除……怎敢闭目……",
            "csh_yangjian": "杨间",
            "#csh_yangjian:die": "死了？……我死的次数，会少吗……",
            "#csh_sailasi:die": "我绝不会……回到那地牢里……",
            "#csh_shencaozhi:die": "一身轻松，待来生……",
            "#csh_shenzhugeguo:die": "仙缘已了，魂入轮回。",
            "#csh_dabing:die": "卧槽……这波，是大冰的落幕……",
            "csh_huaman": "花鬘",
            "#csh_huaman:die": "南中的风……吹散了……",
            /* 2026-10-01 补回：以下 10 个武将的 translate 名在 2026-09-30 拆包时遗漏
               （权威值见 extension.js），导致无名杀内显示为键名、AI 世界 97 人名册缺名。
               单一真值恢复：名字权威回 character/index.js。 */
            "csh_bin": "彬",
            "csh_huangyueying": "黄月英",
            "csh_kuisangti": "奎桑提",
            "csh_liximing": "李曦明",
            "csh_mingrixiang": "明日香",
            "csh_sailasi": "塞拉斯",
            "csh_sake": "萨科",
            "csh_xingganning": "星星甘宁",
            "csh_yuangubafei": "远古八废",
            "csh_zuozhu": "佐助",
        },
                        characterIntro: {
            "csh_huaman": "南中蛮女，花鬘。身着异域戎装，手持柳叶刀，随身携女装与传国玉玺。南蛮入侵于她如归故里，象阵一开，嬉战方休。",
        },
        characterTitle: {
            "csh_huaman": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#f0c070;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(200,140,60,0.55);border-radius:2px;background:linear-gradient(180deg,#1a1208,#2a1e10);text-shadow:0 1px 2px rgba(0,0,0,0.85),0 0 10px rgba(255,180,80,0.4);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>南中蛮裔·象阵嬉战</span>",
            "csh_mingrixiang": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:15px;font-weight:bold;color:#ff9179;letter-spacing:1px;padding:3px 12px;border:1px solid rgba(214,88,58,0.55);border-radius:2px;background:linear-gradient(180deg,#200b08,#3a140d);text-shadow:0 1px 2px rgba(0,0,0,0.85),0 0 10px rgba(255,120,80,0.4);white-space:nowrap;display:inline-block;'>我已经先你一步变成大人了</span>",
"csh_moteng": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#e8d5ff;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(160,100,220,0.55);border-radius:2px;background:linear-gradient(180deg,#1a1028,#2d1a45);text-shadow:0 1px 2px rgba(0,0,0,0.85),0 0 10px rgba(180,120,255,0.35);'>梦魇</span>",
                        "csh_diaochan": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#e8a0bf;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(200,120,160,0.55);border-radius:2px;background:linear-gradient(180deg,#1a1018,#2a1824);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>巧施连环计</span>",
            "csh_liximing": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#e8d5a3;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(200,170,100,0.55);border-radius:2px;background:linear-gradient(180deg,#1a160c,#2a2410);text-shadow:0 1px 2px rgba(0,0,0,0.85),0 0 10px rgba(220,190,100,0.35);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>昭景</span>",
            "csh_xingganning": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#7ec8e3;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,160,200,0.55);border-radius:2px;background:linear-gradient(180deg,#0a1820,#123040);text-shadow:0 1px 2px rgba(0,0,0,0.85),0 0 10px rgba(100,200,255,0.35);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>锦帆破浪·铃影穿涛</span>",
            "csh_yuangubafei": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:15px;font-weight:bold;color:#e8c56a;letter-spacing:1px;padding:3px 12px;border:1px solid rgba(180,140,60,0.55);border-radius:2px;background:linear-gradient(180deg,#1a1408,#2a2210);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>我们八个真强</span>",
            "csh_huangyueying": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>青云鸾飞</span>",
            "csh_bin": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#f0d090;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(200,160,60,0.55);border-radius:2px;background:linear-gradient(180deg,#1a1408,#2a2010);text-shadow:0 1px 2px rgba(0,0,0,0.85),0 0 10px rgba(220,180,60,.45);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>我依然是世一上</span>",
            "csh_zuozhu": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#a8c8f0;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(120,60,200,0.55);border-radius:2px;background:linear-gradient(180deg,#0a0818,#1c1030);text-shadow:0 1px 2px rgba(0,0,0,0.85),0 0 10px rgba(150,80,220,.5);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>宇智波萨斯给</span>",
            "csh_msmy": "<span style='color:#e8d5a3;font-size:16px;font-weight:bold;text-shadow:0 0 6px #c9a227;'>我敢指洛水为誓，你敢吗</span>",
            "csh_qw": "<span style='color:#a0d8ef;font-size:15px;font-style:italic;letter-spacing:1px;'>有伤天和，不伤文和</span>",
            "csh_guohuai": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>雍凉干城·料敌机先</span>",
            "csh_dengai": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>深耕陇亩·偷渡阴平</span>",
            "csh_zhonghui": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#c9a0e8;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(150,90,200,0.5);border-radius:2px;background:linear-gradient(180deg,#150820,#241038);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>少年权数·志在西川</span>",
            "csh_xushu": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>身在曹营·心缄汉月</span>",
            "csh_weizheng": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>以人为镜·可明得失</span>",
            "csh_wolongzhuge": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>未出茅庐·已定三分</span>",
            "csh_simahui": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>水镜澄澈·照尽群英</span>",
            "csh_chengyu": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>算敌于先·伏兵于野</span>",
            "csh_ae": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ff9179;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(214,88,58,0.5);border-radius:2px;background:linear-gradient(180deg,#200b08,#3a140d);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>当阳一喝·退却百万</span>",
            "csh_szc": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#e8c872;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(212,175,55,0.55);border-radius:2px;background:linear-gradient(180deg,#1d1608,#33270f);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>青龙偃月·威震华夏</span>",
            "csh_maochao": "<span style='color:#ffe66d;font-size:18px;font-weight:bold;letter-spacing:0.8px;'>最得意之作</span>",
            "csh_sx": "<span style='color:#ff9f1c;font-size:17px;text-shadow:0 0 5px #ff6b00;'>拼命三郎</span>",
            "csh_guansuo": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>将门虎子·南征之刃</span>",
            "csh_zhaoxiang": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>将门虎女·银枪映雪</span>",
            "csh_lvlingqi": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ff9179;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(214,88,58,0.5);border-radius:2px;background:linear-gradient(180deg,#200b08,#3a140d);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>温侯血脉·焰骨天成</span>",
            "csh_wenyang": "<span style='color:#48cae4;font-size:15px;text-shadow:1px 1px 3px #0077b6;line-height:1.35;letter-spacing:0.5px;'>乐嘉风起残云散<br>万钧雷震万千军</span>",
            "csh_chendao": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>白毦精锐·名亚子龙</span>",
            "csh_guanyinping": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ff9179;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(214,88,58,0.5);border-radius:2px;background:linear-gradient(180deg,#200b08,#3a140d);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>关山虎女·雪恨之锋</span>",
            "csh_chengpu": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ff9179;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(214,88,58,0.5);border-radius:2px;background:linear-gradient(180deg,#200b08,#3a140d);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>江东宿将·火淬醇醪</span>",
            "csh_zhangbao": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#c9a0e8;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(150,90,200,0.5);border-radius:2px;background:linear-gradient(180deg,#150820,#241038);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>黄天当立·咒起风云</span>",
            "csh_xurong": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ff9179;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(214,88,58,0.5);border-radius:2px;background:linear-gradient(180deg,#200b08,#3a140d);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>凉州铁蹄·连破二雄</span>",
            "csh_wy": "<span style='color:#00bbf9;font-size:16px;font-style:italic;text-shadow:1px 1px 2px #005f73;'>武当天才</span>",
            "csh_ngwt": "<span style='color:#8338ec;font-size:18px;font-weight:600;text-shadow:0 0 6px #5a189a;'>雷法天师</span>",
            "csh_dongzhuo": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#e8c872;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(212,175,55,0.55);border-radius:2px;background:linear-gradient(180deg,#1d1608,#33270f);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>郿坞深藏·虎视西凉</span>",
            "csh_shanyuezhiyin": "<span style='color:#ff8c00;font-size:15px;font-weight:bold;text-shadow:0 0 8px #cc5500;'>别问蒲元是谁，都是奥恩敲的</span>",
            "csh_realityfanghao": "<span style='color:#ffd700;font-size:16px;font-weight:bold;text-shadow:0 0 8px #ffaa00,0 0 12px #ff8800;'>开天行道肇纪立极大圣至神仁文义武俊德成功高体天弘道高</span>",
            "csh_feibijiubi": "<span style='color:#ff70a6;font-size:26px;font-style:italic;letter-spacing:1.2px;'>哦对了</span>",
            "csh_kuisangti": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:19px;font-weight:bold;color:#ffd700;letter-spacing:3px;padding:3px 16px;border:1px solid rgba(212,175,55,0.65);border-radius:2px;background:linear-gradient(180deg,#1d1608,#33270f);text-shadow:0 1px 2px rgba(0,0,0,0.85),0 0 10px rgba(255,215,0,0.65),0 0 18px rgba(255,180,0,0.4);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,215,0,0.18);'>纳祖芒荣耀</span>",
            "csh_sailasi": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#9adcf0;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(90,180,210,0.55);border-radius:2px;background:linear-gradient(180deg,#06121c,#0d2836);text-shadow:0 1px 2px rgba(0,0,0,0.9),0 0 10px rgba(140,210,240,0.45);box-shadow:0 2px 6px rgba(0,0,0,0.5),inset 0 0 12px rgba(40,110,150,0.3);'>解脱者·窃法缚链</span>",
            "csh_zhugeqing": "<span style='color:#ffd700;font-size:17px;font-weight:bold;text-shadow:0 0 10px #ffd700,0 0 20px #ff4500,0 0 40px #ff0000;'>你败过吗？</span>",
            "csh_vxs": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#c9a0e8;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(150,90,200,0.5);border-radius:2px;background:linear-gradient(180deg,#150820,#241038);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>构陷宫闱·祸起萧墙</span>",
            "csh_yy": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#c9a0e8;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(150,90,200,0.5);border-radius:2px;background:linear-gradient(180deg,#150820,#241038);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>鬼道通神·邪马台尊</span>",
            "csh_lr": "<span style='color:#00aaff;font-size:18px;font-weight:bold;text-shadow:0 0 8px #0077ff;'>憧憬，距离，懂？</span>",
            "csh_wlk": "<span style='color:#ff595e;font-size:16px;font-weight:bold;text-shadow:0 0 7px #ff0000;'>血在流，一个不留！</span>",
            "csh_doudou": "<span style='font-family:\"Noto Serif SC\",serif;font-size:16px;font-weight:bold;color:#1a1a1a;letter-spacing:2px;border:2px solid #b8860b;border-radius:3px;padding:6px 20px;background:linear-gradient(135deg,#ffd700 0%,#f0c419 25%,#e6a817 50%,#d4881a 75%,#c47a10 100%);box-shadow:inset 0 1px 2px rgba(255,235,150,0.8),inset 0 -2px 4px rgba(0,0,0,0.3),0 3px 8px rgba(0,0,0,0.5),0 1px 0 rgba(255,255,255,0.3);text-shadow:0 1px 1px rgba(255,235,150,0.6),0 -1px 1px rgba(0,0,0,0.4);'>真方圣来了</span>",
            "csh_nailong_juexing": "<span style='color:#8ac926;font-size:18px;font-style:italic;text-shadow:0 0 5px #6a994e;'>捧腹！大笑！</span>",
            "csh_zhuran": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#95d5b2;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(70,150,110,0.5);border-radius:2px;background:linear-gradient(180deg,#08160f,#0d2b1e);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>胆守周身·锋芒暗藏</span>",
            "csh_yujin": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#dde8f0;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(160,180,200,0.45);border-radius:2px;background:linear-gradient(180deg,#10151b,#1d252e);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>毅重之名·晚节之霜</span>",
            "csh_handang": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>三世老臣·弓马娴熟</span>",
            "csh_ls": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>指囷相赠·静水流深</span>",
            "csh_sq": "<span style='color:#ff9f1c;font-size:18px;font-weight:bold;text-shadow:0 0 6px #ffbf69;'>吴王持六剑</span>",
            "csh_sj": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ff9179;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(214,88,58,0.5);border-radius:2px;background:linear-gradient(180deg,#200b08,#3a140d);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>江东猛虎·破虏之志</span>",
            "csh_bfsm": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>曲有误处·周郎一顾</span>",
            "csh_mlm": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>士别三日·刮目相看</span>",
            "csh_lukang": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>西陵长城·社稷之臣</span>",
            "csh_caiyan": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#c9a0e8;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(150,90,200,0.5);border-radius:2px;background:linear-gradient(180deg,#150820,#241038);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>胡笳声断·悲愤成章</span>",
            "csh_caoang": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#e8c872;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(212,175,55,0.55);border-radius:2px;background:linear-gradient(180deg,#1d1608,#33270f);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>宛城火起·让马之德</span>",
            "csh_caochun": "<span style='color:#4cc9f0;font-size:17px;letter-spacing:0.8px;'>IF当初活下来了</span>",
            "csh_shamoke": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ff9179;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(214,88,58,0.5);border-radius:2px;background:linear-gradient(180deg,#200b08,#3a140d);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>五溪之雄·铁蒺藜响</span>",
            "csh_mlb": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#e8c872;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(212,175,55,0.55);border-radius:2px;background:linear-gradient(180deg,#1d1608,#33270f);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>人中吕布·马中赤兔</span>",
            "csh_jjxs": "<span style='font-size:17px;font-weight:bold;'><span style='color:#ff4500;text-shadow:0 0 10px #ff0000,0 0 20px #ff6600;'>火杀伤害高</span> <span style='color:#00bfff;text-shadow:0 0 10px #0080ff,0 0 20px #00ffff;'>雷杀高伤害</span></span>",
            "csh_mmhz": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#e8c872;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(212,175,55,0.55);border-radius:2px;background:linear-gradient(180deg,#1d1608,#33270f);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>引而不发·一弦裂穹</span>",
            "csh_gjs": "<span style='color:#6c757d;font-size:16px;font-style:italic;letter-spacing:1px;'>禁止</span>",
            "csh_gdsn": "<span style='color:#00b4d8;font-size:17px;font-weight:600;text-shadow:0 0 5px #0077b6;'>对高达一号的伟大模仿</span>",
            "csh_dz": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#dde8f0;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(160,180,200,0.45);border-radius:2px;background:linear-gradient(180deg,#10151b,#1d252e);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>雪域圣峰·一眼万年</span>",
            "csh_misida": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ff9179;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(214,88,58,0.5);border-radius:2px;background:linear-gradient(180deg,#200b08,#3a140d);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>四乃禁忌·弹无虚发</span>",
            "csh_gaogan": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#e8c872;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(212,175,55,0.55);border-radius:2px;background:linear-gradient(180deg,#1d1608,#33270f);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>金枝淬火·不让须眉</span>",
            "csh_gy": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ff9179;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(214,88,58,0.5);border-radius:2px;background:linear-gradient(180deg,#200b08,#3a140d);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>三绝归一·雷霆在手</span>",
            "csh_mzj": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#c9a0e8;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(150,90,200,0.5);border-radius:2px;background:linear-gradient(180deg,#150820,#241038);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>洛水惊鸿·翩若游龙</span>",
            "csh_xuchu": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ff9179;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(214,88,58,0.5);border-radius:2px;background:linear-gradient(180deg,#200b08,#3a140d);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>虎痴之勇·裸衣之烈</span>",
            "csh_jzh": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ff9179;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(214,88,58,0.5);border-radius:2px;background:linear-gradient(180deg,#200b08,#3a140d);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>苦肉为饵·烈火为锋</span>",
            "csh_bzt": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ff9179;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(214,88,58,0.5);border-radius:2px;background:linear-gradient(180deg,#200b08,#3a140d);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>盗戟之勇·力负千斤</span>",
            "csh_zhuzhi": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#e8c872;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(212,175,55,0.55);border-radius:2px;background:linear-gradient(180deg,#1d1608,#33270f);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>德玛巨像·魔免之壁</span>",
            "csh_lifeng": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#95d5b2;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(70,150,110,0.5);border-radius:2px;background:linear-gradient(180deg,#08160f,#0d2b1e);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>秉节守土·砥柱中流</span>",
            "csh_lidian": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>忘私之义·先登之勇</span>",
            "csh_zhugeke": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ff9179;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(214,88,58,0.5);border-radius:2px;background:linear-gradient(180deg,#200b08,#3a140d);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>锋芒尽露·众矢之的</span>",
            "csh_wn": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#95d5b2;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(70,150,110,0.5);border-radius:2px;background:linear-gradient(180deg,#08160f,#0d2b1e);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>乌戈之王·藤甲不侵</span>",
            "csh_zhangning": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#95d5b2;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(70,150,110,0.5);border-radius:2px;background:linear-gradient(180deg,#08160f,#0d2b1e);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>黄天之女·符济苍生</span>",
            "csh_daaixianzun": "<span style='font-size:13px;font-weight:bold;color:#fff;letter-spacing:0.7px;padding:5px 12px;border:1px solid rgba(139,0,0,0.8);border-radius:3px;background:linear-gradient(180deg,rgba(80,0,0,0.85) 0%,rgba(139,0,0,0.75) 40%,rgba(178,34,34,0.7) 70%,rgba(80,0,0,0.85) 100%);box-shadow:0 0 6px rgba(139,0,0,0.5),0 2px 4px rgba(0,0,0,0.6),inset 0 0 8px rgba(255,0,0,0.15);text-shadow:0 0 2px #8b0000,0 0 4px #ff0000,0 0 7px #cc0000,0 1px 3px #000;'>人山人海雅座一位</span><br><span style='color:#c9c0a8;font-size:13px;font-weight:normal;letter-spacing:1px;opacity:0.85;'>配音来源木成</span>",
            "csh_youhabahe": "<span style='font-size:18px;font-weight:bold;color:#1a1a2e;letter-spacing:2px;padding:6px 20px;border:2px solid #4a5568;border-radius:2px;background:linear-gradient(135deg,#a0aec0 0%,#e2e8f0 30%,#ffffff 50%,#cbd5e0 70%,#718096 100%);box-shadow:0 0 10px rgba(160,174,192,0.6),0 2px 6px rgba(0,0,0,0.5),inset 0 1px 2px rgba(255,255,255,0.8),inset 0 -2px 3px rgba(0,0,0,0.2);text-shadow:0 1px 2px rgba(255,255,255,0.5),0 -1px 1px rgba(0,0,0,0.3);'>Almighty</span>",
            "csh_shencaozhi": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#b8d4f0;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(110,140,180,0.55);border-radius:2px;background:linear-gradient(180deg,#0a1420,#152238);text-shadow:0 1px 2px rgba(0,0,0,0.85),0 0 10px rgba(120,160,220,0.35);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);display:inline-block;'>才高八斗·七步成诗</span><br><span style='font-size:11px;color:#9aa8b8;opacity:0.8;letter-spacing:1px;'>来源：子琪·天庭</span>",
            "csh_shenzhugeguo": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ffe9a8;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(220,180,100,0.55);border-radius:2px;background:linear-gradient(180deg,#1d1608,#2e2410);text-shadow:0 1px 2px rgba(0,0,0,0.85),0 0 10px rgba(255,220,150,0.4),0 0 20px rgba(255,200,100,0.2);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);display:inline-block;'>仙缘天授·羽化飞升</span><br><span style='font-size:11px;color:#a89880;opacity:0.8;letter-spacing:1px;'>来源：子琪·天庭</span>",
            "csh_jieluji": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#a8e6f0;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(90,170,190,0.55);border-radius:2px;background:linear-gradient(180deg,#071318,#0e2830);text-shadow:0 1px 2px rgba(0,0,0,0.85),0 0 10px rgba(120,200,220,0.35);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);display:inline-block;'>怀橘遗爱·浑天测象</span>",
            "csh_dabing": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:17px;font-weight:400;color:#b8d8e8;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(120,190,220,0.3);border-radius:3px;background:linear-gradient(180deg,rgba(10,25,40,0.85),rgba(20,40,65,0.7));text-shadow:0 1px 2px rgba(0,0,0,0.6);box-shadow:0 1px 4px rgba(0,0,0,0.3);display:inline-block;'>❄ 卧槽冰！ ❄</span>",
            "csh_zhangxingcai": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#c9a0e8;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(150,90,200,0.5);border-radius:2px;background:linear-gradient(180deg,#150820,#241038);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>敬哀皇后·枪动星河</span>",
            "csh_modekaisa": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#b8b8d8;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(140,120,180,0.55);border-radius:2px;background:linear-gradient(180deg,#10101c,#1e1a30);text-shadow:0 1px 2px rgba(0,0,0,0.85),0 0 10px rgba(150,90,220,0.45);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>铁铸亡魂·冥界之主</span>",
            "csh_donk": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ffe66d;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(212,175,55,0.55);border-radius:2px;background:linear-gradient(180deg,#1d1608,#33270f);text-shadow:0 1px 2px rgba(0,0,0,0.85),0 0 8px rgba(255,180,0,0.4);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>扫射神童·一发入魂</span>",
            "csh_lamosi": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#dde8f0;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(160,180,200,0.45);border-radius:2px;background:linear-gradient(180deg,#10151b,#1d252e);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>荆甲重壁·万刃归身</span>",
            "csh_zhouchu": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#8ecae6;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(80,150,190,0.5);border-radius:2px;background:linear-gradient(180deg,#081318,#0d2430);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>义除三害·砥砺自新</span>",
            "csh_yangjian": "<span style='display:inline-block;font-family:KaiTi,STKaiti,SimKai,serif;font-size:22px;font-weight:900;color:#e00101;letter-spacing:6px;white-space:nowrap;transform:skewX(-4deg);text-shadow:0 0 2px #1a0000,0 0 5px #ff0000,0 0 14px rgba(255,0,0,.75),0 0 26px rgba(150,0,0,.5);'>恐怖复苏</span>",
            "csh_sake": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#b06ee8;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(140,60,200,0.55);border-radius:2px;background:linear-gradient(180deg,#12061f,#251038);text-shadow:0 1px 2px rgba(0,0,0,0.9),0 0 10px rgba(190,120,255,0.5);box-shadow:0 2px 6px rgba(0,0,0,0.5),inset 0 0 12px rgba(100,20,160,0.3);'>恶魔小丑·真假难辨</span>",
            "csh_theshy": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ff9179;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(214,88,58,0.5);border-radius:2px;background:linear-gradient(180deg,#200b08,#3a140d);text-shadow:0 1px 2px rgba(0,0,0,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>剑魔天降·只进不退</span>",
            "csh_zywoo": "<span style='font-family:Impact,Arial Black,sans-serif;font-size:18px;font-weight:900;color:#ff4444;letter-spacing:2px;text-shadow:0 0 4px #000,0 0 12px #ff0000,0 0 20px #aa0000;'>FUCKING GOAT</span>",
            "csh_sunshangxiang": "<span style='font-family:KaiTi,STKaiti,SimKai,serif;font-size:16px;font-weight:bold;color:#ffd7a8;letter-spacing:2px;padding:3px 14px;border:1px solid rgba(214,150,80,0.55);border-radius:2px;background:linear-gradient(180deg,#201408,#3a2410);text-shadow:0 1px 2px rgba(0,0,0,0.85),0 0 10px rgba(255,180,90,0.35);box-shadow:0 2px 6px rgba(0,0,0,0.4),inset 0 0 10px rgba(255,255,255,0.06);'>弓腰姬</span>",
        },
        characterSort: {
            "mode_extension_池子魔将": {
                "csh_cuifeng": ["csh_gy","csh_chengpu","csh_mlb","csh_jjxs","csh_mmhz","csh_chendao","csh_sx","csh_xuchu","csh_handang","csh_wlk","csh_zhuran","csh_doudou","csh_wenyang","csh_caochun","csh_jzh","csh_lukang","csh_zhugeke","csh_lidian","csh_guanyinping","csh_wolongzhuge","csh_zhangxingcai","csh_bfsm","csh_theshy","csh_zywoo"],
                "csh_jingting": ["csh_maochao","csh_dabing","csh_donk","csh_sake","csh_gjs","csh_shencaozhi","csh_sailasi"],
                "csh_fulan": ["csh_chengyu","csh_youhabahe","csh_weizheng","csh_lr","csh_xushu","csh_qw","csh_xurong","csh_mzj","csh_zhangbao","csh_yy","csh_wy","csh_diaochan"],
                "csh_huichuan": ["csh_zhouchu","csh_ngwt","csh_shamoke","csh_vxs","csh_bzt","csh_zhugeqing","csh_ls","csh_yujin","csh_feibijiubi"],
                "csh_fuguang": ["csh_huangyueying","csh_gaogan","csh_zhangning","csh_daaixianzun","csh_jieluji","csh_shanyuezhiyin","csh_caiyan","csh_caoang","csh_lifeng","csh_simahui"],
                "csh_jinhuo": ["csh_dz","csh_wn","csh_lamosi","csh_zhuzhi","csh_gdsn","csh_dongzhuo","csh_kuisangti"],
                "csh_zhoutian": ["csh_mingrixiang","csh_bin","csh_yuangubafei","csh_xingganning","csh_liximing","csh_sunshangxiang","csh_guansuo","csh_lvlingqi","csh_realityfanghao","csh_dengai","csh_guohuai","csh_mlm","csh_nailong_juexing","csh_modekaisa","csh_yangjian","csh_shenzhugeguo","csh_szc","csh_sj","csh_misida","csh_ae","csh_zhaoxiang","csh_msmy","csh_zhonghui","csh_sq","csh_zuozhu","csh_moteng","csh_huaman"],
                "csh_qunyou_lunwai": ["csh_pingfan"],
                "csh_pingxing_shang": ["csh_m_shen_caopi","csh_m_shen_xunyu","csh_m_mb_caomao","csh_m_pot_dongzhao","csh_m_pot_yuji","csh_m_pot_weiyan","csh_m_pot_taishici","csh_m_peixiu","csh_m_star_dongzhuo","csh_m_yangbiao","csh_m_chenshi","csh_m_sb_diaochan","csh_m_sb_liubei","csh_m_ol_sb_jiangwei","csh_m_shen_sunce","csh_m_shen_guojia","csh_m_shen_ganning","csh_m_shen_lusu","csh_m_sb_fazheng","csh_m_sb_caocao","csh_m_star_zhangchunhua","csh_m_star_sunjian","csh_m_star_fazheng","csh_m_pot_zhouyu","csh_m_pot_xinxianying","csh_m_mb_simazhao","csh_m_sunsháo","csh_m_sp_duyu","csh_m_shen_taishici","csh_m_shen_huatuo","csh_m_dc_sb_huanggai","csh_m_sb_huanggai","csh_m_sb_yuanshao","csh_m_clan_zhonghui","csh_m_mb_shen_jiangwei","csh_m_liuyan","csh_m_guoyuan","csh_m_cy_lingju","csh_m_re_xiahoudun","csh_m_shichangshi","csh_m_xizhicai","csh_m_sb_caopi","csh_m_zhanglu","csh_m_mb_zhangfen","csh_m_yanghuiyu","csh_m_sp_caosong","csh_m_fuqian","csh_m_yanxiang","csh_m_sp_yanxiang","csh_m_zhugejing","csh_m_mb_sp_guanqiujian","csh_m_ol_guanhai","csh_m_dc_sunhuan","csh_m_ol_puyuan","csh_m_tw_wenyang","csh_m_mb_wenyang","csh_m_puyuan"],
                "csh_pingxing_xia": ["csh_m_caomao","csh_m_liuhui","csh_m_zhouyi","csh_m_zhaozhi","csh_m_re_sunyi","csh_m_sxrm_huatuo","csh_m_sxrm_xunyu","csh_m_yanghong","csh_m_sxrm_luxun","csh_m_yue_zhouyu","csh_m_yue_daqiao","csh_m_jsrg_liubei","csh_m_jsrg_zhangju","csh_m_jsrg_wenyang","csh_m_sxrm_caocao","csh_m_sxrm_zhouyu"],
                "csh_pingxing_yinjian": ["csh_m_shen_jiangwei","csh_m_shen_dengai","csh_m_shen_xuzhu","csh_m_shen_zhangfei","csh_m_caojinyu","csh_m_shen_pangtong","csh_m_wu_zhugeliang","csh_m_sxrm_guanyu","csh_m_wu_huangfusong","csh_m_yue_caiwenji","csh_m_yue_caozhi"],
            },
        },
    };
